-- Migration 031 (UP) — Re-add users.password_hash for the phone+password admin
-- login path (owner/admin/staff/super_admin sign in with phone + a password an
-- operator sets via the dbadmin CLI). It is NULLABLE: phone-first player rows and
-- any roled user without a provisioned password keep NULL and authenticate via the
-- existing OTP / booking-session paths. The value stored is always a bcrypt hash —
-- never plaintext (enforced in application + CLI code, not by the column type).
--
-- This reverses migration 007 (which dropped the legacy column) for a NEW purpose;
-- no other column or table is touched. Paired with 031_add_password_hash.down.sql.
-- Idempotent (IF NOT EXISTS).
ALTER TABLE users ADD COLUMN IF NOT EXISTS password_hash TEXT;
